ARG PHP_VERSION=8.3
FROM php:${PHP_VERSION}-fpm-alpine

LABEL maintainer="Esdras Caleb"

ENV MOODLE_DIR="/var/www/moodle"
ENV MOODLE_DATA="/var/www/moodledata"

# 1. Dependências de Execução (Runtime)
# Removido python3, jq e bibliotecas de dev após a instalação
RUN apk add --no-cache \
    bash nginx supervisor git unzip coreutils \
    libpng libjpeg-turbo freetype libzip \
    icu-libs libxml2 libpq oniguruma \
    libxslt libsodium libmemcached zlib openssl \
    graphviz aspell ghostscript poppler-utils

# 2. Instalação de Extensões e Dependências de Compilação (Build-time)
RUN apk add --no-cache --virtual .build-deps \
    $PHPIZE_DEPS \
    libpng-dev libjpeg-turbo-dev freetype-dev libzip-dev \
    icu-dev libxml2-dev postgresql-dev oniguruma-dev \
    libxslt-dev libsodium-dev libmemcached-dev zlib-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
        gd intl zip soap opcache pdo pdo_pgsql pgsql mysqli pdo_mysql exif bcmath xsl sodium \
    && pecl install redis memcached \
    && docker-php-ext-enable redis memcached \
    # Limpeza imediata para reduzir o tamanho da imagem
    && apk del .build-deps \
    && rm -rf /tmp/pear

# 3. Configurações Opcache (Otimizadas para Moodle)
RUN { \
        echo 'opcache.memory_consumption=256'; \
        echo 'opcache.interned_strings_buffer=16'; \
        echo 'opcache.max_accelerated_files=20000'; \
        echo 'opcache.revalidate_freq=60'; \
        echo 'opcache.fast_shutdown=1'; \
        echo 'opcache.enable_cli=1'; \
        echo 'opcache.jit=tracing'; \
        echo 'opcache.jit_buffer_size=100M'; \
    } > /usr/local/etc/php/conf.d/opcache-recommended.ini

# 4. Estrutura de pastas e arquivos
RUN mkdir -p $MOODLE_DATA /var/log/supervisor $MOODLE_DIR \
    && chown -R www-data:www-data $MOODLE_DATA \
    && chmod 777 $MOODLE_DATA

COPY nginx.conf /etc/nginx/nginx.conf
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 80
WORKDIR $MOODLE_DIR

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]